### ISSUE TITLE
Performance regression

### ISSUE THREAD

**Issue by phisco** [tmzane/musttag#55]
On https://github.com/upbound/provider-aws we've seen a major performance degradation using `musttag` through golangci-lint lately (v1.52.2) , but that's also reproducible running it on its own (v0.7.0). See https://github.com/golangci/golangci-lint/issues/3910 for more details.

TL;DR: From the tracing syscall graph and some experiments run by @ldez it looks like the issue is with the number of `go list` calls done here: https://github.com/tmzane/musttag/blob/main/utils.go. Could be that our repository is kind of pathological, given that we are running it without issues on https://github.com/crossplane/crossplane, but still it's definitely some kind of regression, because it was running fine with older versions.

**Comment by ldez** [comment]
Hello,

It's related to [the fix](https://github.com/tmzane/musttag/pull/22) of #17.

**Comment by tmzane** [comment]
Thank you for the report! Also, sorry for the late reply 😅

@ldez is right, it was caused by the mentioned fix, which was dirty but necessary.

Once `go/analysis` includes the module info, we will be able to get rid of this hack (and the performance regression that comes with it). Until then, we need it to prevent a lot of false-positives 😢

Currently, there are two `go list` calls, with the second one being optional as its role is purely cosmetic (prettifying paths). If we drop it, the total number of syscalls will be reduced to half, which might be just enough!

**Comment by ldez** [comment]
@tmzane take a look at my PR, I think you don't need all the directories.

**Comment by tmzane** [comment]
@phisco please take a look at [`v0.7.1`](https://github.com/tmzane/musttag/releases/tag/v0.7.1), which includes the fix 🎉

@ldez thanks again ❤️

**Comment by phisco** [comment]
Awesome, thank you both! 👏👏👏
